version: '3'

services:
  web:
    hostname: web
    build: .
    ports:
      - "3000:3000"
    command: bash -c "rails db:schema:dump"
    command: bash -c "bundle exec rake db:migrate"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
